spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@192.168.0.171:1521/HCP19CDEV
    url: jdbc:oracle:thin:@192.168.0.171:1521/HCP19CDEV
    username: hcp
    password: hcp
  #type-aliases-package=
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器端口号
    port: 6378
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    #password: "123456"
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 6
        # 连接池中的最小空闲连接
        min-idle: 4
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
#日志配置
logging:
  config: classpath:log4j2-test.xml
server:
  port: 8082