spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@192.168.0.171:1521/HCP19CDEV
    url: jdbc:oracle:thin:@192.168.0.210:1521/HCPPROD
    username: hcp
    password: hcp
  #type-aliases-package=
mybatis:
  mapper-locations: classpath:mapping/*.xml